// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZKeyhvuYUlBcdqylVIexJOZdQ7-S4lFI',
    appId: '1:492936842220:web:de1c69381e413074c34ec9',
    messagingSenderId: '492936842220',
    projectId: 'eacc-mobile-app',
    authDomain: 'eacc-mobile-app.firebaseapp.com',
    storageBucket: 'eacc-mobile-app.firebasestorage.app',
    measurementId: 'G-S9GL3J0R9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD270_y2v0bEboQfuN94bOjolN-UoGvkjo',
    appId: '1:492936842220:android:d4a225330630e03ac34ec9',
    messagingSenderId: '492936842220',
    projectId: 'eacc-mobile-app',
    storageBucket: 'eacc-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6aNZjF32iii0Z_fsZzVkUL2X1KfDQv8',
    appId: '1:492936842220:ios:e4ca566f6d08733ac34ec9',
    messagingSenderId: '492936842220',
    projectId: 'eacc-mobile-app',
    storageBucket: 'eacc-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.chattEacc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ6aNZjF32iii0Z_fsZzVkUL2X1KfDQv8',
    appId: '1:492936842220:ios:e4ca566f6d08733ac34ec9',
    messagingSenderId: '492936842220',
    projectId: 'eacc-mobile-app',
    storageBucket: 'eacc-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.chattEacc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZKeyhvuYUlBcdqylVIexJOZdQ7-S4lFI',
    appId: '1:492936842220:web:f4b52333cfbe5a34c34ec9',
    messagingSenderId: '492936842220',
    projectId: 'eacc-mobile-app',
    authDomain: 'eacc-mobile-app.firebaseapp.com',
    storageBucket: 'eacc-mobile-app.firebasestorage.app',
    measurementId: 'G-QE7ETCPZSY',
  );
}
